### ISSUE TITLE
WebUI control is broken after update

### ISSUE THREAD

**Issue by mrbluebrett** [FujiHeatPump/esphome-fujitsu#12]
After the latest ESPhome update, my webui doesn't show controls for the AC as it showed before.
In HA works fine and i can control correctly...
See screenshot:
![fujitsu](https://github.com/FujiHeatPump/esphome-fujitsu/assets/77754688/98c03bf0-a3c9-4366-ad67-2b0fb5c570c1)

**Comment by rabbit-aaron** [comment]
the webui has never showed any control for me when i first developed it.

**Comment by mrbluebrett** [comment]
Aftel last ESPhome update, webui shows controls again. So I guess the issue was with ESPhome itself...
