### ISSUE TITLE
Get current temperature measured by the indoor unit

### ISSUE THREAD

**Issue by thaenan** [FujiHeatPump/esphome-fujitsu#18]
Hi,

It seems that regardless of the setup of the temperature sensor on the AC controller - indoor unit or thermo sensor on the remote controller - the ambient temperature retrieved by the script and displayed is always the one from the controller.

Is there any way to get the one from the indoor unit? (Which in my case the one used to control the AC).

Thanks! Cheers.

![Screenshot_20240806-112353](https://github.com/user-attachments/assets/555db077-0d7f-4882-a5cc-65b9ada5e5ee)

**Comment by rabbit-aaron** [comment]
i don't have the same hardware as you do so i cannot help you on this.
            currentState.controllerTemp = ff.controllerTemp; 
   I used this setup and my hvac takes my master controller temp and report that back.
